null	LIBRE	LIBRE
null	A.A.M.M. - ASOCIACION A...MUTUAL DEL MOTOCICLISTA	A.A.M.M. - ASOCIACION A...MUTUAL DEL MOTOCICLISTA	habilitada
null	A.M.F.F.A.	A.M.F.F.A.	habilitada
null	ACA SALUD	ACA SALUD	habilitada
null	AMTCYA - ASOCIACIÓN MUT...BAJADORES DEL CUERO Y A	AMTCYA - ASOCIACIÓN MUT...BAJADORES DEL CUERO Y A	habilitada
null	APPI SRL - OSPPCYQ	APPI SRL - OSPPCYQ	habilitada
null	APRES (INTERNADOS)	APRES (INTERNADOS)	habilitada
null	APRES (SERVICIOS MEDICOS S.A.) AMBULATORIO	APRES (SERVICIOS MEDICOS S.A.) AMBULATORIO	habilitada
null	APSOT	APSOT	habilitada
null	ASOCIACION MUTUAL DE PROTECCION FAMILIAR (AMPF)	ASOCIACION MUTUAL DE PROTECCION FAMILIAR (AMPF)	habilitada
null	ASOCIACION ECLESIATICA SAN PEDRO	ASOCIACION ECLESIATICA SAN PEDRO	habilitada
null	BANCO PROVINCIA	BANCO PROVINCIA	habilitada
null	CASA (CAJA DE ABOGADOS)	CASA (CAJA DE ABOGADOS)	habilitada
null	COLEGIO DE ESCRIBANOS PCIA.DE BS.AS.	COLEGIO DE ESCRIBANOS PCIA.DE BS.AS.	habilitada
null	COMEI (CAJA DE ODONTOLOGOS)	COMEI (CAJA DE ODONTOLOGOS)	habilitada
null	CONSOLIDAR SALUD (EUROMEDICA)	CONSOLIDAR SALUD (EUROMEDICA)	habilitada
null	CORTE SUPREMA	CORTE SUPREMA	habilitada
null	DASMI - UNIVERSIDAD NACIONAL DE LUJAN	DASMI - UNIVERSIDAD NACIONAL DE LUJAN	habilitada
null	DOCTHOS	DOCTHOS	habilitada
null	ELECTRICISTAS NAVALES	ELECTRICISTAS NAVALES	habilitada
null	FEDERADA SALUD (EX 25 DE JUNIO)	FEDERADA SALUD (EX 25 DE JUNIO)	habilitada
null	FEMEBA SALUD - FLORENCIO VARELA -	FEMEBA SALUD - FLORENCIO VARELA -	habilitada
null	FUTBOLISTAS ARGENTINOS AGREMIADOS	FUTBOLISTAS ARGENTINOS AGREMIADOS	habilitada
null	GALENO	GALENO	habilitada
null	HEALT MEDICAL - CAMI TANDIL	HEALT MEDICAL - CAMI TANDIL	habilitada
null	HOSPITAL ITALIANO	HOSPITAL ITALIANO	habilitada
null	I-MEDICAL II PLUS, III...ILVER MASTER Y SILVER +	I-MEDICAL II PLUS, III...ILVER MASTER Y SILVER +	habilitada
null	I-MEDICAL (PLAN JOVEN I Y II ) PLAN INTEGRAL	I-MEDICAL (PLAN JOVEN I Y II ) PLAN INTEGRAL	habilitada
null	I-MEDICAL OSMEDICA PLUS	I-MEDICAL OSMEDICA PLUS	habilitada
null	I-MEDICAL OSMEDICA ECO Y PROSALUD	I-MEDICAL OSMEDICA ECO Y PROSALUD	habilitada
null	INSTITUTO MEDICO LABOR	INSTITUTO MEDICO LABOR	habilitada
null	INTEGRAL SRL-OSPAT (O S... LA ACTIVIDAD DEL TURF)	INTEGRAL SRL-OSPAT (O S... LA ACTIVIDAD DEL TURF)	habilitada
null	INTELIGENT MEDICAL S.R.L.	INTELIGENT MEDICAL S.R.L.	habilitada
null	IOSE INSTITUTO OBRA SOC...EJERCITO (EN ACTIVIDAD)	IOSE INSTITUTO OBRA SOC...EJERCITO (EN ACTIVIDAD)	habilitada
null	IOSE INSTITUTO OBRA SOC...ERCITO (GRUPO FAMILIAR)	IOSE INSTITUTO OBRA SOC...ERCITO (GRUPO FAMILIAR)	habilitada
null	JERARQUICO SALUD (PLAN PMI)	JERARQUICO SALUD (PLAN PMI)	habilitada
null	LUIS PASTEUR	LUIS PASTEUR	habilitada
null	LUZ Y FUERZA - PLAN BASICO	LUZ Y FUERZA - PLAN BASICO	habilitada
null	LUZ Y FUERZA - PLAN ESPECIAL	LUZ Y FUERZA - PLAN ESPECIAL	habilitada
null	MANDAR SALUD - DAS (PER... CONGRESO DE LA NACION)	MANDAR SALUD - DAS (PER... CONGRESO DE LA NACION)	habilitada
null	MAPFRE SALUD	MAPFRE SALUD	habilitada
null	MEDICUS (CONVENIO FORD)	MEDICUS (CONVENIO FORD)	habilitada
null	MEDICUS (PLAN CORPORATE Y FAMILY)	MEDICUS (PLAN CORPORATE Y FAMILY)	habilitada
null	MEDICUS - MEDICAR	MEDICUS - MEDICAR	habilitada
null	MEDIFE	MEDIFE	habilitada
null	O.P.S.A. A.T.S.A. LA PLATA	O.P.S.A. A.T.S.A. LA PLATA	habilitada
null	O.S.A.P. (OBRA SOCIAL ACEROS PARANA)	O.S.A.P. (OBRA SOCIAL ACEROS PARANA)	habilitada
null	O.S.P.E.R.Y.H.R.A	O.S.P.E.R.Y.H.R.A	habilitada
null	O.S.P.FE.S.I.Q.Y P. (O....IND.IND.QUIM.Y PETROQ.)	O.S.P.FE.S.I.Q.Y P. (O....IND.IND.QUIM.Y PETROQ.)	habilitada
null	O.S.P.I.M. INDUSTRIA MOLINERA	O.S.P.I.M. INDUSTRIA MOLINERA	habilitada
null	O.S.S.I.M.R.A (ASIMRA)	O.S.S.I.M.R.A (ASIMRA)	habilitada
null	OBRA SOCIAL DE FOTOGRAFOS (OSFOT)	OBRA SOCIAL DE FOTOGRAFOS (OSFOT)	habilitada
null	OBRA SOCIAL E.W.HOPE	OBRA SOCIAL E.W.HOPE	habilitada
null	OMINT	OMINT	habilitada
null	OPDEA	OPDEA	habilitada
null	OSAPM	OSAPM	habilitada
null	OSDE (ORGANIZACIÓN DE S...S DIRECTOS EMPRESARIOS)	OSDE (ORGANIZACIÓN DE S...S DIRECTOS EMPRESARIOS)	habilitada
null	OSDEL	OSDEL	habilitada
null	OSDIPP INDUSTRIA PRIVADA DEL PETROLEO	OSDIPP INDUSTRIA PRIVADA DEL PETROLEO	habilitada
null	OSETYA (OBRA SOCIAL DE...ADOS TEXTILES Y AFINES)	OSETYA (OBRA SOCIAL DE...ADOS TEXTILES Y AFINES)	habilitada
null	OSIAD SALUD (O.S. PERS.... DESMONTADORA Y AFINES)	OSIAD SALUD (O.S. PERS.... DESMONTADORA Y AFINES)	habilitada
null	OSMEBA	OSMEBA	habilitada
null	OSMEBA (INTERNADOS)	OSMEBA (INTERNADOS)	habilitada
null	OSMITA	OSMITA	habilitada
null	OSPE (OBRA SOCIAL DE PETROLEROS)	OSPE (OBRA SOCIAL DE PETROLEROS)	habilitada
null	OSPEGAP	OSPEGAP	habilitada
null	OSPIA (O.S. PERSONAL D...RIA DE LA ALIMENTACION)	OSPIA (O.S. PERSONAL D...RIA DE LA ALIMENTACION)	habilitada
null	OSPOCE INTEGRAL PLAN ARRAYAN	OSPOCE INTEGRAL PLAN ARRAYAN	habilitada
null	OSPOCE INTEGRAL PLAN CEIBO	OSPOCE INTEGRAL PLAN CEIBO	habilitada
null	OSPRA - PERSONAL DE PRE... LA REPUBLICA ARGENTINA	OSPRA - PERSONAL DE PRE... LA REPUBLICA ARGENTINA	habilitada
null	OSSEG (O.S.SEGUROS)	OSSEG (O.S.SEGUROS)	habilitada
null	OSSEG PLAN ESPECIAL (O.S. SEGUROS)	OSSEG PLAN ESPECIAL (O.S. SEGUROS)	habilitada
null	OSTEL (PLAN AZUL Y PLAN...CINDIÓ CONV. 31/01/2011	OSTEL (PLAN AZUL Y PLAN...CINDIÓ CONV. 31/01/2011	habilitada
null	OSVARA (VENDEDORES AMBULANTES)	OSVARA (VENDEDORES AMBULANTES)	habilitada
null	PAMI VETERANOS DE GUERRA	PAMI VETERANOS DE GUERRA	habilitada
null	PERSONAL DE FARMACIA	PERSONAL DE FARMACIA	habilitada
null	PERSONAL DE IMPRENTAS (OSPIDA)	PERSONAL DE IMPRENTAS (OSPIDA)	habilitada
null	PRIMED S.A - PRIMEDIC ... B, B1, CA Y SUPERIOR	PRIMED S.A - PRIMEDIC ... B, B1, CA Y SUPERIOR	habilitada
null	PRIMEDIC - PRIMED PLANE...ASIC Y OTROS NO INCLUID	PRIMEDIC - PRIMED PLANE...ASIC Y OTROS NO INCLUID	habilitada
null	PRIMEDIC SALUD PLAN "ELITE"	PRIMEDIC SALUD PLAN "ELITE"	habilitada
null	RED ARGENTINA DE SALUD (RAS)	RED ARGENTINA DE SALUD (RAS)	habilitada
null	SADAIC	SADAIC	habilitada
null	SANAR S.A.	SANAR S.A.	habilitada
null	SCIS PLAN MN OMBU - (EX AMSA)	SCIS PLAN MN OMBU - (EX AMSA)	habilitada
null	SCIS - SC250	SCIS - SC250	habilitada
null	SCIS PLAN SC100	SCIS PLAN SC100	habilitada
null	SCIS SC500- SC550 - SC600-	SCIS SC500- SC550 - SC600-	habilitada
null	SERV. Y PRESTACIONES ME...ERS.IND.CUERO Y AFINES)	SERV. Y PRESTACIONES ME...ERS.IND.CUERO Y AFINES)	habilitada
null	SERVESALUD (OS.PERS.DIR.IND.CERVECERA Y MALTERA)	SERVESALUD (OS.PERS.DIR.IND.CERVECERA Y MALTERA)	habilitada
null	SERVICIOS Y PRESTACIONE...(O.SOC.PERS.LADRILLERO)	SERVICIOS Y PRESTACIONE...(O.SOC.PERS.LADRILLERO)	habilitada
null	SINDICATO OPERADORES CINEMATOGRAFICOS	SINDICATO OPERADORES CINEMATOGRAFICOS	habilitada
null	SWISS MEDICAL GROUP	SWISS MEDICAL GROUP	habilitada
null	SWISS MEDICAL- PLAN EMBAJADA ITALIANA	SWISS MEDICAL- PLAN EMBAJADA ITALIANA	habilitada
null	TECHINT (FSST)	TECHINT (FSST)	habilitada
null	U.N.L.P.	U.N.L.P.	habilitada
null	UNION PERSONAL PLAN DORADO	UNION PERSONAL PLAN DORADO	habilitada
null	UNION PERSONAL PLAN PLATINO	UNION PERSONAL PLAN PLATINO	habilitada
null	OSPA	OSPA OBRA SOCIAL PORTUARIOS ARGENTINOS DE MAR DEL PLATA	habilitada
null	OSALARA	OBRA SOCIAL DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA ARGENTINA	habilitada
null	OSSEG	OBRA SOCIAL DE LA ACTIVIDAD DE SEGUROS, REASEGUROS,CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA	habilitada